[package]
name = "time-macro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[features]
profiling = []

[dependencies]
syn = { version = "2.0.65", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"